#testbuild
#minimal script to install and run acouplasi tests on linux

before_script: 
  #create and activate the python 3 env
  - conda config --set always_yes yes --set changeps1 no
  - conda create -n test_py39 python=3.9
  - source activate test_py39
  - conda install gcc_linux-64
  - python3 --version
  - uname -a
  
after_script: 
  # delete the test enviroment 
  - conda env remove --name test_py39
  
stages:
  - build
  - test
  
build:
  # install acouplasi
  stage: build
  script:
    - echo "Building"
    - python3 setup.py install

test:
  #install and run tests
  stage: test
  script:
    - echo "Testing"
    - python3 setup.py install
    - python3 -c 'import acouplasi'
    - chmod +x ./tests/run_tests.sh
    - cd ./tests/
    - bash run_tests.sh
    

