#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep  2 18:15:46 2020

@author: radmann
"""

import traitlets as tr
import numpy as np

class PlateArrangement(tr.HasTraits):
    '''
    Parant class for all types of plate resonator configurations.
    '''
    